-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 13:17:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kineclinic_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kineclinic_db` ;

-- -----------------------------------------------------
-- Schema kineclinic_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kineclinic_db` ;
USE `kineclinic_db` ;

-- -----------------------------------------------------
-- Table `kineclinic_db`.`treatments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kineclinic_db`.`treatments` ;

CREATE TABLE IF NOT EXISTS `kineclinic_db`.`treatments` (
  `treatment_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`treatment_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kineclinic_db`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kineclinic_db`.`patients` ;

CREATE TABLE IF NOT EXISTS `kineclinic_db`.`patients` (
  `patient_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `medical_history` LONGTEXT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kineclinic_db`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kineclinic_db`.`schedule` ;

CREATE TABLE IF NOT EXISTS `kineclinic_db`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `hours` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`schedule_id`),
  UNIQUE INDEX `hours_UNIQUE` (`hours` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kineclinic_db`.`workers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kineclinic_db`.`workers` ;

CREATE TABLE IF NOT EXISTS `kineclinic_db`.`workers` (
  `worker_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`worker_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kineclinic_db`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kineclinic_db`.`sessions` ;

CREATE TABLE IF NOT EXISTS `kineclinic_db`.`sessions` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `treatment_id` INT NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  `schedule_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `status` ENUM("Pendiente", "Cerrada") NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`session_id`),
  INDEX `fk_sessions_treatments_idx` (`treatment_id` ASC) VISIBLE,
  INDEX `fk_sessions_patients1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_sessions_schedule1_idx` (`schedule_id` ASC) VISIBLE,
  INDEX `fk_sessions_workers1_idx` (`worker_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_treatments`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `kineclinic_db`.`treatments` (`treatment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `kineclinic_db`.`patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `kineclinic_db`.`schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_workers1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `kineclinic_db`.`workers` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kineclinic_db`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kineclinic_db`.`history` ;

CREATE TABLE IF NOT EXISTS `kineclinic_db`.`history` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`history_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
